name: LogicLobby
version: '${project.version}'
main: de.frinshhd.logiclobby.Main
api-version: '1.19'
author: FrinshHD
softdepend: [ SuperVanish, PremiumVanish, CloudNet-Bridge ]

permissions:
  logiclobby.admin.updateNotify:
    default: op
  logiclobby.admin.reload:
    default: op
    children:
      - logiclobby.admin
  logiclobby.admin.version:
    default: op
    children:
      - logiclobby.admin
  logiclobby.admin:
    default: op
  logiclobby.command.fly:
    default: op
  logiclobby.command.fly.others:
    default: op
  logiclobby.command.spawn:
    default: true
  logiclobby.admin.build:
    default: false
  logiclobby.command.lobbyswitcher:
    default: true
  logiclobby.gadget.teleportBow:
    default: op

commands:
  logiclobby:
    description: "Main command for LogicLobby"
    usage: "/logiclobby"
    aliases: "ll"
  fly:
    description: "Toggle fly mode"
    usage: "/fly"
  spawn:
    description: "Teleport to the spawn"
    usage: "/spawn"
  lobbyswitcher:
    description: "Open the lobby switcher"
    usage: "/lobbyswitcher"